### ISSUE TITLE
Decomposition of records

### ISSUE THREAD

**Issue by Zekfad** [schultek/type_plus#1]
Hello, thank you for awesome module!
In recent version there was added records support, is it possible to decompose record and differentiate named, positional and optional arguments?

Currently it's possible to treat records like a generic class
```dart
  [
    <A, B>(f) => f<(A, B,)>(),
    <A, B>(f) => f<(A, {B named})>(),
  ].forEach(TypePlus.addFactory);

  print(typeOf<(int, int, )>().args); // [int, int]
  print(typeOf<(int, {int named})>().args); // same
```

**Comment by schultek** [comment]
Hi, can you give me some more details on your use-case and what you would want to do?

**Comment by Zekfad** [comment]
Hi, thank you for responding!

I'd like to write binary (un)packer based on records similar to python `struct` but powered by strong types.

E.g. `T unpack<T extends Record>(TypedData data)` and extension on record to pack it.

**Comment by schultek** [comment]
Have you checked out dart_mappable?


Did you already test out how to dynamically construct a record? From my experiments this isn't possible. You need to know the shape of a record statically in order to construct an instance of it.

**Comment by Zekfad** [comment]
Now that you pointed out that.
I can think of creating unnamed ones like this: `(U,V) collapse<U,V>(U x, V y) => (x,y)` and similarity up to 5.
But I guess it's not really possible to create named record dynamically (maybe with mirrors, but that's not really an option in my opinion)

Then maybe I should limit records is my api only to group a small number of elements.

Thank you for your help!

**Comment by schultek** [comment]
Yeah I had the same problem when adding records support to dart_mappable. I wanted to do it dynamically but it wasn't possible.
